name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4

      - name: Run Tests
        run: go test .

  build:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4

      - name: Build
        run: go build -o main

      - name: Archive main artifact
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: main

      - name: Archive goapp.service artifact
        uses: actions/upload-artifact@v2
        with:
          name: goapp.service
          path: goapp.service

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download main artifact
        uses: actions/download-artifact@v2
        with:
          name: main

      - name: Download goapp.service artifact
        uses: actions/download-artifact@v2
        with:
          name: goapp.service

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 192.168.105.3 >> ~/.ssh/known_hosts

      - name: Stop existing service on server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@192.168.105.3 "sudo systemctl stop goapp.service || true"

      - name: Copy files to server
        run: |
          scp -i ~/.ssh/id_rsa main ${{ secrets.SSH_USERNAME }}@192.168.105.3:
          scp -i ~/.ssh/id_rsa goapp.service ${{ secrets.SSH_USERNAME }}@192.168.105.3:

      - name: Start service on server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@192.168.105.3 "sudo cp goapp.service /etc/systemd/system/"
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@192.168.105.3 "sudo systemctl daemon-reload"
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@192.168.105.3 "sudo systemctl start goapp.service"
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@192.168.105.3 "sudo systemctl enable goapp.service"
